@startuml
class ApplicationView <<partial>> {
    + ApplicationView()
    + ShowSheetView(sheetViewModel:SheetViewModel) : void
    + ShowToolWindow(content:UserControl, allowDuplicates:bool) : void
    # <<override>> OnInitialized(e:EventArgs) : void
    - AddNewSheetButtonClicked(sender:object, e:RoutedEventArgs) : void
    - AdjustWindowSize() : void
    - GoToSheetButtonClicked(sender:object, e:RoutedEventArgs) : void
    - MaximizeButtonClick(sender:object, e:RoutedEventArgs) : void
    - MinimizeButtonClick(sender:object, e:RoutedEventArgs) : void
    - OnCloseButtonClicked(sender:object, e:RoutedEventArgs) : void
    - OpenSpecialEditPanelButtonClick(sender:object, e:RoutedEventArgs) : void
    - OpenTextEditPanelButtonClick(sender:object, e:RoutedEventArgs) : void
    - ShowCollectionManagerButtonClick(sender:object, e:RoutedEventArgs) : void
    - ShowFunctionManagerButtonClick(sender:object, e:RoutedEventArgs) : void
    - ShowHelpButtonClick(sender:object, e:RoutedEventArgs) : void
    - ShowLogWindowButtonClick(sender:object, e:RoutedEventArgs) : void
    - TextBoxPreviewKeyDown(sender:object, e:KeyEventArgs) : void
    - ToggleEditPanelButtonClick(sender:object, e:RoutedEventArgs) : void
    - TogglePanLockButtonClick(sender:object, e:RoutedEventArgs) : void
    - TogglePopulateCellDependencyButtonClick(sender:object, e:RoutedEventArgs) : void
    - TogglePopulateCollectionDependencyButtonClick(sender:object, e:RoutedEventArgs) : void
    - ToggleTriggerCellDependencyButtonClick(sender:object, e:RoutedEventArgs) : void
    - ToggleTriggerCollectionDependencyButtonClick(sender:object, e:RoutedEventArgs) : void
    - WindowPreviewKeyDown(sender:object, e:KeyEventArgs) : void
    - WindowSizeChanged(sender:object, e:SizeChangedEventArgs) : void
    - Window_SizeChanged(sender:object, e:SizeChangedEventArgs) : void
}
class "Dictionary`2"<T1,T2> {
}
Window <|-- ApplicationView
ApplicationView o-> "_sheetViews<SheetViewModel,SheetView>" "Dictionary`2"
ApplicationView --> "ActiveSheetView" SheetView
ApplicationView --> "ApplicationSettings" ApplicationSettings
@enduml
