@startuml
class TitleBarSheetNavigation <<partial>> {
    - isRenameingSheet : bool = false
    - sheetBeingRenamed : string
    + TitleBarSheetNavigation()
    - AddNewSheetButtonClicked(sender:object, e:RoutedEventArgs) : void
    - GoToSheetButtonClicked(sender:object, e:RoutedEventArgs) : void
}
UserControl <|-- TitleBarSheetNavigation
@enduml
