using Cell.Core.Common;
using Cell.ViewModel.Application;
using System.Text;

namespace Cell.ViewModel.ToolWindow
{
    /// <summary>
    /// A view model for the log window which displays logs generated by the application.
    /// </summary>
    public class LogWindowViewModel : ToolWindowViewModel
    {
        private readonly StringBuilder _logBufferBuilder = new();
        /// <summary>
        /// Gets the default height of this tool window when it is shown.
        /// </summary>
        public override double DefaultHeight => 400;

        /// <summary>
        /// Gets the default width of this tool window when it is shown.
        /// </summary>
        public override double DefaultWidth => 400;

        /// <summary>
        /// The log string that is displayed in the UI.
        /// </summary>
        public string LogBuffer => _logBufferBuilder.ToString();

        /// <summary>
        /// Gets the minimum height this tool window is allowed to be reized to.
        /// </summary>
        public override double MinimumHeight => 100;

        /// <summary>
        /// Gets the minimum width this tool window is allowed to be reized to.
        /// </summary>
        public override double MinimumWidth => 100;

        /// <summary>
        /// Provides a list of commands to display in the title bar of the tool window.
        /// </summary>
        public override List<CommandViewModel> ToolBarCommands =>
        [
            new("Clear", ClearBuffer) { ToolTip = "Clears the list of logs." }
        ];

        /// <summary>
        /// Gets the string displayed in top bar of this tool window.
        /// </summary>
        public override string ToolWindowTitle => "Logs";

        /// <summary>
        /// Clears out the log buffer and notifies the UI that it has changed.
        /// </summary>
        public void ClearBuffer()
        {
            _logBufferBuilder.Clear();
            NotifyPropertyChanged(nameof(LogBuffer));
        }

        /// <summary>
        /// Occurs when the tool window is really being closed.
        /// </summary>
        public override void HandleBeingClosed()
        {
            Logger.Instance.LogAdded -= AddLog;
            ClearBuffer();
        }

        /// <summary>
        /// Occurs when the tool window is being shown.
        /// </summary>
        public override void HandleBeingShown()
        {
            Logger.Instance.LogAdded += AddLog;
            foreach (var log in Logger.Instance.Logs.Take(100))
            {
                AddLog(log);
            }
        }

        private void AddLog(string log)
        {
            _logBufferBuilder.Insert(0, log + "\n");
            if (_logBufferBuilder.Length > 10000)
            {
                _logBufferBuilder.Remove(_logBufferBuilder.Length - 1000, 1000);
            }
            NotifyPropertyChanged(nameof(LogBuffer));
        }
    }
}
