using Cell.Core.Common;
using Cell.ViewModel.Application;
using System.Text;

namespace Cell.ViewModel.ToolWindow
{
    /// <summary>
    /// A view model for the log window which displays logs generated by the application.
    /// </summary>
    public class LogWindowViewModel : ToolWindowViewModel
    {
        private readonly string _title;

        public LogWindowViewModel(Logger logger, string title = "Logs")
        {
            _title = title;
            _logger = logger;
            ToolBarCommands.Add(new("Clear", ClearBuffer) { ToolTip = "Clears the list of logs." });
        }

        private readonly StringBuilder _logBufferBuilder = new();
        private readonly Logger _logger;

        /// <summary>
        /// Gets the default height of this tool window when it is shown.
        /// </summary>
        public override double DefaultHeight => 400;

        /// <summary>
        /// Gets the default width of this tool window when it is shown.
        /// </summary>
        public override double DefaultWidth => 400;

        /// <summary>
        /// The log string that is displayed in the UI.
        /// </summary>
        public string LogBuffer => _logBufferBuilder.ToString();

        /// <summary>
        /// Gets the minimum height this tool window is allowed to be reized to.
        /// </summary>
        public override double MinimumHeight => 100;

        /// <summary>
        /// Gets the minimum width this tool window is allowed to be reized to.
        /// </summary>
        public override double MinimumWidth => 100;

        /// <summary>
        /// Gets the string displayed in top bar of this tool window.
        /// </summary>
        public override string ToolWindowTitle => _title;

        /// <summary>
        /// Clears out the log buffer and notifies the UI that it has changed.
        /// </summary>
        public void ClearBuffer()
        {
            _logBufferBuilder.Clear();
            NotifyPropertyChanged(nameof(LogBuffer));
        }

        /// <summary>
        /// Occurs when the tool window is really being closed.
        /// </summary>
        public override void HandleBeingClosed()
        {
            _logger.LogAdded -= AddLog;
            ClearBuffer();
        }

        /// <summary>
        /// Occurs when the tool window is being shown.
        /// </summary>
        public override void HandleBeingShown()
        {
            _logger.LogAdded += AddLog;
            foreach (var log in _logger.Logs.Take(100))
            {
                AddLog(log);
            }
        }

        private void AddLog(string log)
        {
            _logBufferBuilder.AppendLine(log);
            if (_logBufferBuilder.Length > 10000)
            {
                _logBufferBuilder.Remove(_logBufferBuilder.Length - 1000, 1000);
            }
            NotifyPropertyChanged(nameof(LogBuffer));
        }
    }
}
