@startuml
class CellTriggerManager <<static>> {
    + {static} CellTriggered(cell:CellModel, editContext:EditContext) : void
    + {static} StartMonitoringCell(model:CellModel) : void
    + {static} StopMonitoringCell(model:CellModel) : void
}
class "Dictionary`2"<T1,T2> {
}
CellTriggerManager o-> "_cellsBeingEdited<string,CellModel>" "Dictionary`2"
@enduml
