@startuml
class CellPopulateManager {
    + {static} GetAllCollectionSubscriptions(subscriber:CellModel) : List<string>
    + {static} GetAllLocationSubscriptions(subscriber:CellModel) : List<string>
    + {static} NotifyCellValueUpdated(cell:CellModel) : void
    + {static} NotifyCollectionUpdated(userCollectionName:string) : void
    + {static} StartMonitoringCellForUpdates(model:CellModel) : void
    + {static} StopMonitoringCellForUpdates(model:CellModel) : void
    + {static} SubscribeToCollectionUpdates(subscriber:CellModel, collectionName:string) : void
    + {static} SubscribeToCollectionUpdates(subscriber:ListCellViewModel, collectionName:string) : void
    + {static} SubscribeToUpdatesAtLocation(subscriber:CellModel, sheet:string, row:int, column:int) : void
    + {static} UnsubscribeFromAllCollectionUpdates(model:CellModel) : void
    + {static} UnsubscribeFromAllLocationUpdates(model:CellModel) : void
    + {static} UnsubscribeFromCollectionUpdates(model:CellModel, collectionName:string) : void
    + {static} UnsubscribeFromCollectionUpdates(subscriber:ListCellViewModel, collectionName:string) : void
    + {static} UnsubscribeFromUpdatesAtLocation(model:CellModel, locationString:string) : void
    - {static} GetAllSubscriptions(model:CellModel, subscriberToReferenceMap:Dictionary<CellModel, Dictionary<string, int>>) : List<string>
    - {static} SubscribeToReference(subscriber:CellModel, reference:string, referenceToSubscriberMap:Dictionary<string, Dictionary<CellModel, int>>, subscriberToReferenceMap:Dictionary<CellModel, Dictionary<string, int>>) : void
    - {static} UnsubscribeFromAllReferences(model:CellModel, referenceToSubscriberMap:Dictionary<string, Dictionary<CellModel, int>>, subscriberToReferenceMap:Dictionary<CellModel, Dictionary<string, int>>) : void
    - {static} UnsubscribeFromReference(model:CellModel, locationString:string, referenceToSubscriberMap:Dictionary<string, Dictionary<CellModel, int>>, subscriberToReferenceMap:Dictionary<CellModel, Dictionary<string, int>>) : void
}
class "Dictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
CellPopulateManager o-> "_cellsBeingUpdated<string,CellModel>" "Dictionary`2"
CellPopulateManager o-> "_cellsToNotifyOnCollectionUpdates<string,Dictionary<CellModel, int>>" "Dictionary`2"
CellPopulateManager o-> "_cellsToNotifyOnLocationUpdates<string,Dictionary<CellModel, int>>" "Dictionary`2"
CellPopulateManager o-> "_collectionsBeingUpdated<string>" "List`1"
CellPopulateManager o-> "_collectionSubcriptionsMadeByCells<CellModel,Dictionary<string, int>>" "Dictionary`2"
CellPopulateManager o-> "_listCellsToUpdateWhenCollectionsChange<string,List<ListCellViewModel>>" "Dictionary`2"
CellPopulateManager o-> "_locationSubcriptionsMadeByCells<CellModel,Dictionary<string, int>>" "Dictionary`2"
@enduml
