@startuml
class EditContext {
    + EditContext(propertyName:string, newValue:object, oldValue:object)
    + EditContext(reason:string)
    + NewValue : object <<get>>
    + OldValue : object <<get>>
    + PropertyName : string <<get>>
    + Reason : string <<get>>
}
EditContext o-> "EditDate" DateTime
@enduml
