@startuml
class PluginContext {
    + <<const>> PluginContextArgumentName : string = "c"
    + Index : int <<get>> <<set>>
    + GetCell(cellForSheet:CellModel, row:int, column:int) : CellModel
    + GetCell(cellForSheet:CellModel, row:int, column:int, rowRangeEnd:int, columnRangeEnd:int) : CellRange
    + GetCell(sheet:string, row:int, column:int) : CellModel
    + GetCell(sheet:string, row:int, column:int, rowRangeEnd:int, columnRangeEnd:int) : CellRange
    + GetUserList(collection:string) : UserList<T>
    + GoToCell(cell:CellModel) : void
    + GoToSheet(sheetName:string) : void
}
PluginContext o-> "_application" ApplicationViewModel
PluginContext o-> "E" EditContext
@enduml
