@startuml
class RoslynCompiler {
    - <<readonly>> _typeName : string = "Plugin.Program"
    + RoslynCompiler(syntax:SyntaxTree, typesToReference:Type[])
    + Compile() : Type
    - {static} GetRuntimeMetadataReference() : PortableExecutableReference
    - GetMetadataReferenceForType(type:Type) : PortableExecutableReference
}
RoslynCompiler --> "_compilation" CSharpCompilation
@enduml
