@startuml
class CellClipboard {
    - _centerOfCopy : CellModel?
    - _copyTextOnly : bool = false
    + CopySelectedCells(activeSheet:SheetViewModel, copyTextOnly:bool) : void
    + PasteCopiedCells(activeSheet:SheetViewModel) : void
    - {static} PasteCopiedCell(pasteIntoCell:CellViewModel, cellToPaste:CellModel, centerOfCopy:CellModel) : void
    - {static} PasteCopiedCellTextOnly(pasteIntoCell:CellViewModel, cellToPaste:CellModel, centerOfCopy:CellModel) : void
    - {static} PasteSingleCell(cellToPaste:CellModel, cellToReplace:CellModel) : void
    - {static} TryGetCellToReplace(pasteIntoCell:CellViewModel, cellToPaste:CellModel, centerOfCopy:CellModel, cellToReplace:CellModel) : bool
}
class "IEnumerable`1"<T> {
}
CellClipboard o-> "_clipboard<CellModel>" "IEnumerable`1"
@enduml
