@startuml
class ColorAdjuster {
    + {static} AdjustBrightness(hexColor:string, brightnessFactor:float) : string
    + {static} GetHighlightColor(backgroundColor:Color, alpha:byte) : Color
    - {static} HSLToHexColor(hue:float, saturation:float, lightness:float) : string
    - {static} HexColorToHSL(hexColor:string, hue:float, saturation:float, lightness:float) : void
    - {static} AdjustLightness(brightnessFactor:float, lightness:float) : float
    - {static} ColorToHSL(red:int, green:int, blue:int, hue:float, saturation:float, lightness:float) : void
    - {static} ColorToHSL(red:float, green:float, blue:float, hue:float, saturation:float, lightness:float) : void
    - {static} GetLightness(max:float, min:float) : float
    - {static} GetSaturation(lightness:float, max:float, min:float, delta:float) : float
    - {static} GetHue(redPercent:float, greenPercent:float, bluePercent:float, max:float, delta:float) : float
    - {static} HSLToRGBColor(hue:float, saturation:float, lightness:float, red:int, green:int, blue:int) : void
    - {static} HueToRGB(temp1:float, temp2:float, hue:float) : float
}
@enduml
