@startuml
class RelayCommand {
    + RelayCommand(execute:Action<object?>)
    + CanExecute(parameter:object?) : bool
    + Execute(parameter:object?) : void
}
class "Predicate`1"<T> {
}
class "Action`1"<T> {
}
ICommand <|-- RelayCommand
RelayCommand o-> "_canExecute<object?>" "Predicate`1"
RelayCommand o-> "_execute<object?>" "Action`1"
@enduml
