@startuml
class Utilities <<static>> <<partial>> {
    + {static} CopyPublicProperties(source:object, target:object, blacklist:string[]) : void
    - {static} CopyProperty(source:object, target:object, blacklist:string[], targetType:Type, sourceProperty:PropertyInfo) : void
    + {static} GenerateUnqiueId(length:int) : string
    + {static} GetHashFromString(read:string) : ulong
    + {static} GetTypesInNamespace(assembly:Assembly, nameSpace:string) : Type[]
    + {static} GetUnqiueLocationString(sheet:string, row:int, column:int) : string
    + {static} GetUnqiueLocationString(model:CellModel) : string
    + {static} <<partial>> IsHexidecimalColorCode() : Regex
    + {static} TryParseStringIntoThickness(stringThickness:string, thickness:Thickness) : bool
}
@enduml
