@startuml
class ApplicationSettings {
    - <<const>> ApplicationSettingsSaveDirectory : string = "Application"
    - <<const>> ApplicationSettingsSaveFile : string = "Settings.json"
    - {static} _instance : ApplicationSettings?
    - codeEditorHeight : double = 400
    - codeEditorWidth : double = 400
    - functionManagerWindowHeight : double = 400
    - functionManagerWindowWidth : double = 400
    - logWindowHeight : double = 400
    - logWindowWidth : double = 400
    - highlightPopulateCellDependencies : bool = true
    - highlightPopulateCollectionDependencies : bool = true
    - highlightTriggerCellDependencies : bool = true
    - highlightTriggerCollectionDependencies : bool = true
    - lastLoadedSheet : string = "Default"
    + ApplicationSettings()
    + CodeEditorHeight : double <<get>> <<set>>
    + CodeEditorWidth : double <<get>> <<set>>
    + FunctionManagerWindowHeight : double <<get>> <<set>>
    + FunctionManagerWindowWidth : double <<get>> <<set>>
    + LogWindowHeight : double <<get>> <<set>>
    + LogWindowWidth : double <<get>> <<set>>
    + HighlightPopulateCellDependencies : bool <<get>> <<set>>
    + HighlightPopulateCollectionDependencies : bool <<get>> <<set>>
    + HighlightTriggerCellDependencies : bool <<get>> <<set>>
    + HighlightTriggerCollectionDependencies : bool <<get>> <<set>>
    + LastLoadedSheet : string <<get>> <<set>>
    + {static} CreateInstance() : ApplicationSettings
    - {static} Load() : ApplicationSettings?
    - Save() : void
}
PropertyChangedBase <|-- ApplicationSettings
ApplicationSettings o-> "codeEditorDockPosition" Dock
ApplicationSettings --> "Instance" ApplicationSettings
ApplicationSettings --> "CodeEditorDockPosition" Dock
@enduml
