@startuml
class PluginFunctionModel {
    - <<const>> codeFooter : string = "\n}}}"
    - <<const>> codeHeader : string = "using System; using System.Linq; using System.Collections.Generic; using Cell.Model; using Cell.Model.Plugin; using Cell.ViewModel; using Cell.Execution; using Cell.ViewModel.Cells.Types;\n\nnamespace Plugin { public class Program { public static "
    - <<const>> methodHeader : string = " PluginMethod(PluginContext c, CellModel cell) {\n"
    - _code : string
    - _name : string
    - _returnType : string
    + PluginFunctionModel()
    + PluginFunctionModel(name:string, code:string, returnType:string)
    + Code : string <<get>> <<set>>
    + Fingerprint : ulong <<get>>
    + FullCode : string <<get>>
    + Name : string <<get>> <<set>>
    + ReturnType : string <<get>> <<set>>
}
PropertyChangedBase <|-- PluginFunctionModel
@enduml
