@startuml
class UserCollectionModel {
    - _sortAndFilterFunctionName : string
    - name : string
    + UserCollectionModel()
    + UserCollectionModel(name:string, type:string, basedOnCollection:string)
    + BasedOnCollectionName : string <<get>> <<set>>
    + ItemTypeName : string <<get>> <<set>>
    + ItemTypeOrBasedOnCollectionName : string <<get>>
    + Name : string <<get>> <<set>>
    + SortAndFilterFunctionName : string <<get>> <<set>>
}
PropertyChangedBase <|-- UserCollectionModel
@enduml
