@startuml
class CollectionReferenceToCodeSyntaxRewriter {
    + IsCollectionName(input:string) : bool
    + <<override>> Visit(node:SyntaxNode?) : SyntaxNode?
}
class "Func`2"<T1,T2> {
}
class "Predicate`1"<T> {
}
class "List`1"<T> {
}
CSharpSyntaxRewriter <|-- CollectionReferenceToCodeSyntaxRewriter
CollectionReferenceToCodeSyntaxRewriter o-> "CollectionReferences<string>" "List`1"
CollectionReferenceToCodeSyntaxRewriter o-> "_getDataTypeFromCollectionNameFunction<string,string>" "Func`2"
CollectionReferenceToCodeSyntaxRewriter o-> "_isCollectionPredicate<string>" "Predicate`1"
CollectionReferenceToCodeSyntaxRewriter o-> "Result" CompileResult
@enduml
