@startuml
class CollectionReferenceSyntaxWalker <<partial>> {
    + {static} TryGetCollectionReferenceFromNode(node:SyntaxNode?, collectionReference:string) : bool
    + <<override>> Visit(node:SyntaxNode?) : void
}
class "List`1"<T> {
}
CSharpSyntaxWalker <|-- CollectionReferenceSyntaxWalker
CollectionReferenceSyntaxWalker o-> "CollectionReferences<string>" "List`1"
@enduml
