@startuml
class BudgetCategoryItem {
    - _localAmount : double = 0
    - _localCategory : string
    - _localPeriodLength : int = 1
    - _localPeriodType : string = "Days"
    - _localPriority : int = 0
    - _localRollover : bool = false
    + Amount : double <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + PeriodLength : int <<get>> <<set>>
    + PeriodType : string <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Rollover : bool <<get>> <<set>>
    + GetPeriod(forDate:DateTime) : TimeSpan
    <<override>> + ToString() : string
}
PluginModel <|-- BudgetCategoryItem
BudgetCategoryItem o-> "_localStartDate" DateTime
BudgetCategoryItem --> "StartDate" DateTime
@enduml
