@startuml
class PluginModel {
    - {static} _cachedDataTypeNames : List<string>?
    - _id : string
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
    + ID : string <<get>> <<set>>
    + {static} GetPluginDataTypeNames() : IEnumerable<string>
    + OnPropertyChanged(propertyName:string) : void
    <<override>> + ToString() : string
}
INotifyPropertyChanged <|-- PluginModel
@enduml
