@startuml
class TransactionItem {
    - _localAmount : double = 0
    - _localCategory : string
    - _localNotes : string
    + Amount : double <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + Notes : string <<get>> <<set>>
    <<override>> + ToString() : string
}
PluginModel <|-- TransactionItem
TransactionItem o-> "_localDate" DateTime
TransactionItem --> "Date" DateTime
@enduml
