@startuml
class ColumnCellViewModel {
    + ColumnCellViewModel(model:CellModel, sheetViewModel:SheetViewModel)
    + <<override>> BackgroundColorHex : string <<get>> <<set>>
    + <<override>> Text : string <<get>> <<set>>
    + <<override>> Width : double <<get>> <<set>>
    + {static} GetColumnName(columnNumber:int) : string
    + AddColumnToTheLeft() : void
    + AddColumnToTheRight() : void
    + DeleteColumn() : void
    - AddColumnAt(index:int) : void
    - GetAllCellsAtOrToTheRightOf(column:int) : List<CellModel>
    - IncrementColumnOfAllAtOrToTheRightOf(column:int, amount:int) : void
    - InsertColumnAtIndex(index:int) : void
    - ModelPropertyChanged(sender:object?, e:System.ComponentModel.PropertyChangedEventArgs) : void
}
SpecialCellViewModel <|-- ColumnCellViewModel
@enduml
