@startuml
class FunctionManagerWindowViewModel {
    - filterSheet : string = "All"
    - filterString : string
    - includePopulateFunctions : bool = true
    - includeTriggerFunctions : bool = true
    - selectedFunction : FunctionViewModel?
    + FunctionManagerWindowViewModel(pluginFunctions:ObservableCollection<FunctionViewModel>)
    + FilterSheet : string <<get>> <<set>>
    + FilterString : string <<get>> <<set>>
    + IncludePopulateFunctions : bool <<get>> <<set>>
    + IncludeTriggerFunctions : bool <<get>> <<set>>
    - FilterVisibleFunctions() : void
    - FunctionsCollectionChanged(sender:object?, e:System.Collections.Specialized.NotifyCollectionChangedEventArgs) : void
    - IsFunctionIncludedInFilter(function:FunctionViewModel) : bool
}
class "ObservableCollection`1"<T> {
}
ResizeableToolWindowViewModel <|-- FunctionManagerWindowViewModel
FunctionManagerWindowViewModel --> "_functions<FunctionViewModel>" "ObservableCollection`1"
FunctionManagerWindowViewModel o-> "Functions<FunctionViewModel>" "ObservableCollection`1"
FunctionManagerWindowViewModel o-> "ReferencedCollectionsByTheSelectedFunction<string>" "ObservableCollection`1"
FunctionManagerWindowViewModel --> "SelectedFunction" FunctionViewModel
FunctionManagerWindowViewModel o-> "SheetNameOptions<string>" "ObservableCollection`1"
FunctionManagerWindowViewModel o-> "UsersOfTheSelectedFunction<CellModel>" "ObservableCollection`1"
@enduml
