@startuml
class CellContentEditWindow <<partial>> {
    + CellContentEditWindow()
    + GetTitle() : string
    + GetToolBarCommands() : List<CommandViewModel>
    + HandleBeingClosed() : bool
    - {static} IndexSelectedCells() : void
    - EditPopulateFunctionButtonClicked(sender:object, e:RoutedEventArgs) : void
    - EditTriggerFunctionButtonClicked(sender:object, e:RoutedEventArgs) : void
    - TextBoxKeyDown(sender:object, e:KeyEventArgs) : void
    - TextBoxPreviewKeyDown(sender:object, e:KeyEventArgs) : void
}
UserControl <|-- CellContentEditWindow
IToolWindow <|-- CellContentEditWindow
CellContentEditWindow --> "RequestClose" Action
@enduml
