@startuml
class CellFormatEditWindow <<partial>> {
    + CellFormatEditWindow()
    + {static} AddColorsToColorPicker(colorPicker:ColorPicker, colors:List<string>, brightnessFactor:float) : void
    + GetTitle() : string
    + GetToolBarCommands() : List<CommandViewModel>
    + HandleBeingClosed() : bool
    - {static} GetCellsInRectangle(startRow:int, startColumn:int, endRow:int, endColumn:int, sheetName:string) : List<CellModel>
    - {static} MergeCells(cells:List<CellViewModel>) : void
    - {static} SetMergedWithToCellsId(cellsToMerge:List<CellModel>, topLeftCell:CellViewModel) : void
    - ChangeCellTypeCellClicked(sender:object, e:RoutedEventArgs) : void
    - ColorPicker_Loaded(sender:object, e:RoutedEventArgs) : void
    - ComboBox_DropDownClosed(sender:object, e:EventArgs) : void
    - CreateBackupButtonClicked(sender:object, e:RoutedEventArgs) : void
    - CreateNewColumnToTheLeftButtonClicked(sender:object, e:RoutedEventArgs) : void
    - CreateNewColumnToTheRightButtonClicked(sender:object, e:RoutedEventArgs) : void
    - CreateNewRowAboveButtonClicked(sender:object, e:RoutedEventArgs) : void
    - CreateNewRowBelowButtonClicked(sender:object, e:RoutedEventArgs) : void
    - DeleteColumnButtonClicked(sender:object, e:RoutedEventArgs) : void
    - DeleteRowButtonClicked(sender:object, e:RoutedEventArgs) : void
    - MergeAcrossButtonClicked(sender:object, e:RoutedEventArgs) : void
    - MergeButtonClicked(sender:object, e:RoutedEventArgs) : void
    - MergeDownButtonClicked(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToBottomButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToBottomLeftButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToBottomRightButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToCenterButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToLeftButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToRightButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToTopButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToTopLeftButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetAlignmentToTopRightButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetTextAlignmentToCenterButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetTextAlignmentToLeftButtonClick(sender:object, e:RoutedEventArgs) : void
    - SetTextAlignmentToRightButtonClick(sender:object, e:RoutedEventArgs) : void
    - TextBoxKeyDown(sender:object, e:KeyEventArgs) : void
    - UnmergeButtonClicked(sender:object, e:RoutedEventArgs) : void
}
UserControl <|-- CellFormatEditWindow
IToolWindow <|-- CellFormatEditWindow
CellFormatEditWindow --> "RequestClose" Action
@enduml
