@startuml
class FunctionManagerWindow <<partial>> {
    + FunctionManagerWindow(viewModel:FunctionManagerWindowViewModel)
    + GetHeight() : double
    + GetTitle() : string
    + GetToolBarCommands() : List<CommandViewModel>
    + GetWidth() : double
    + HandleBeingClosed() : bool
    + SetHeight(height:double) : void
    + SetWidth(width:double) : void
    - DeleteFunctionButtonClicked(sender:object, e:System.Windows.RoutedEventArgs) : void
    - EditFunctionFromCellsContextButtonClick(sender:object, e:System.Windows.RoutedEventArgs) : void
    - GoToCellButtonClick(sender:object, e:System.Windows.RoutedEventArgs) : void
    - RemoveFunctionReferenceFromCellButtonClick(sender:object, e:System.Windows.RoutedEventArgs) : void
}
UserControl <|-- FunctionManagerWindow
IResizableToolWindow <|-- FunctionManagerWindow
FunctionManagerWindow --> "_viewModel" FunctionManagerWindowViewModel
FunctionManagerWindow --> "RequestClose" Action
@enduml
