@startuml
class LogWindow <<partial>> {
    + LogWindow(viewModel:LogWindowViewModel)
    + GetHeight() : double
    + GetTitle() : string
    + GetToolBarCommands() : List<CommandViewModel>
    + GetWidth() : double
    + HandleBeingClosed() : bool
    + SetHeight(height:double) : void
    + SetWidth(width:double) : void
}
UserControl <|-- LogWindow
IResizableToolWindow <|-- LogWindow
LogWindow --> "_viewModel" LogWindowViewModel
LogWindow --> "RequestClose" Action
@enduml
