@startuml
class ButtonCellViewModel {
    - _buttonClickedCommand : ICommand?
    + ButtonClicked() : void
}
CellViewModel <|-- ButtonCellViewModel
ButtonCellViewModel --> "ButtonClickedCommand" ICommand
@enduml
