@startuml
class GraphCellViewModel {
    - _addingPoint : bool = false
    + GraphCellViewModel(model:CellModel, sheet:SheetViewModel)
    + MaxPoints : int <<get>> <<set>>
    + MaxPointsString : string <<get>> <<set>>
    + <<override>> Text : string <<get>> <<set>>
    + UpdatePointsScaling() : void
    <<internal>> {static} ScaleAndCenterPoints(points:List<Point>, targetWidth:int, targetHeight:int) : PointCollection
    - UpdatePointsFromCellText() : void
}
class "List`1"<T> {
}
CellViewModel <|-- GraphCellViewModel
GraphCellViewModel o-> "_rawDataPoints<Point>" "List`1"
GraphCellViewModel o-> "DataPoints" PointCollection
@enduml
