@startuml
class SheetView <<partial>> {
    + PanAndZoomCanvas : PanAndZoomCanvas?
    - _currentCellMouseIsOver : CellViewModel?
    - _selectingCells : bool = false
    - _selectionStart : CellViewModel?
    + SheetView()
    - CanSelectCell(cell:CellModel?) : bool
    - CellPreviewMouseDown(sender:object, e:MouseButtonEventArgs) : void
    - CellPreviewMouseMove(sender:object, e:MouseEventArgs) : void
    - CellPreviewMouseUp(sender:object, e:MouseButtonEventArgs) : void
    - PanZoomCanvasLoaded(sender:object, e:RoutedEventArgs) : void
    - TextBoxKeyDown(sender:object, e:KeyEventArgs) : void
}
UserControl <|-- SheetView
SheetView --> "SheetViewModel" SheetViewModel
@enduml
